name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --verbose

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
