name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Semgrep Scan
        uses: semgrep/semgrep-action@v1
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

      - name: Build Inventory API Image
        run: |
          docker build -t inventory-api:latest ./inventory-api
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: inventory-api:latest
          format: table
